window.AGENT_ACTIVITY = {
  "_meta": {
    "schema": 1,
    "note": "Live agent activity overlay. Idle entries fall back to dashboard/agent_status.js seed data.",
    "updated_at": "2026-06-23T08:57:35Z"
  },
  "entries": [
    {
      "agent": "orchestrator",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "claude-orchestrator",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "claude-researcher",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "claude-coder",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "claude-qa",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "claude-security",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "agy",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "agy-researcher",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "agy-coder",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "agy-qa",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "codex",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "codex-coder",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "codex-qa",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    },
    {
      "agent": "codex-security",
      "task_id": null,
      "model": null,
      "effort": null,
      "current_task": null,
      "status": "idle",
      "started_at": null,
      "updated_at": "2026-06-23T08:57:35Z",
      "reason": "",
      "session_usage_pct": 0,
      "usage": null
    }
  ]
};